// <auto-generated/>
namespace Game.Shared.Generated
{
	using System;
	public enum ItemId
	{
		Clover3Leaf = 0,
		CrownChest = 1,
		BlueBag = 2,
		GiftBoxBlue = 3,
		GoldMedal = 4,
		Heart = 5,
		KeyGold = 6,
		PantsIcon = 7,
		PurpleGem = 8,
	}
}
